$dirs = @"
public
public/blog
auth
dashboards
dashboards/admin
dashboards/admin/users
dashboards/admin/lawyers
dashboards/admin/courts
dashboards/admin/cases
dashboards/admin/consultations
dashboards/admin/finance
dashboards/admin/ai
dashboards/admin/content
dashboards/admin/reports
dashboards/admin/settings
dashboards/lawyer
dashboards/lawyer/firm
dashboards/lawyer/consultations
dashboards/lawyer/cases
dashboards/lawyer/tools
dashboards/lawyer/schedule
dashboards/lawyer/earnings
dashboards/client
dashboards/client/vault
dashboards/client/konsultasi
dashboards/client/cases
dashboards/client/pembayaran
dashboards/judge
dashboards/judge/cases
dashboards/judge/sidang
konsultasi
resources
resources/kumpulan-yurisprudensi
resources/perundang-undangan
resources/templates
courts
cases
ai
notifications
logs
security
assets
assets/css
assets/js
assets/js/core
assets/js/auth
assets/js/security
assets/js/realtime
assets/js/ai
assets/js/integrations
assets/js/admin
assets/js/lawyer
assets/js/client
assets/js/judge
assets/images
assets/images/avatars
assets/images/courts
assets/images/banners
assets/images/vectors
assets/images/brand
assets/locales
api
api/middlewares
api/controllers
api/models
api/services
api/routes
data
utils
config
scripts
docs
docs/manuals
tests
tests/e2e
tests/integration
tests/unit
docker
.github
.github/workflows
"@

$files = @"
public/index.html
public/about.html
public/layanan.html
public/harga.html
public/panduan.html
public/kontak.html
public/faq.html
public/kebijakan-privasi.html
public/syarat-ketentuan.html
public/karir.html
public/blog/index.html
public/blog/detail.html
public/404.html
auth/login.html
auth/register-client.html
auth/register-lawyer.html
auth/register-success.html
auth/verifikasi-akun.html
auth/kyc-verification.html
auth/lupa-password.html
auth/reset-password.html
auth/2fa-verification.html
auth/logout.html
auth/unauthorized.html
dashboards/admin/dashboard.html
dashboards/admin/users/list.html
dashboards/admin/users/create.html
dashboards/admin/users/edit.html
dashboards/admin/users/detail.html
dashboards/admin/users/kyc-verifications.html
dashboards/admin/lawyers/list.html
dashboards/admin/lawyers/create.html
dashboards/admin/lawyers/edit.html
dashboards/admin/lawyers/approval.html
dashboards/admin/lawyers/performance.html
dashboards/admin/lawyers/withdrawals.html
dashboards/admin/courts/list.html
dashboards/admin/courts/create.html
dashboards/admin/courts/edit.html
dashboards/admin/courts/map-management.html
dashboards/admin/cases/list.html
dashboards/admin/cases/assign-lawyer.html
dashboards/admin/cases/assign-judge.html
dashboards/admin/cases/disputes.html
dashboards/admin/cases/monitoring.html
dashboards/admin/consultations/list.html
dashboards/admin/consultations/analytics.html
dashboards/admin/finance/transactions.html
dashboards/admin/finance/invoices.html
dashboards/admin/finance/taxes.html
dashboards/admin/finance/reports.html
dashboards/admin/ai/training.html
dashboards/admin/ai/logs.html
dashboards/admin/ai/model-metrics.html
dashboards/admin/ai/moderation.html
dashboards/admin/content/articles.html
dashboards/admin/content/categories.html
dashboards/admin/content/pages.html
dashboards/admin/reports/statistik.html
dashboards/admin/reports/perkara.html
dashboards/admin/reports/user-activity.html
dashboards/admin/settings/system.html
dashboards/admin/settings/roles.html
dashboards/admin/settings/permissions.html
dashboards/admin/settings/integrations.html
dashboards/admin/settings/audit-logs.html
dashboards/lawyer/dashboard.html
dashboards/lawyer/profile.html
dashboards/lawyer/kyc-upload.html
dashboards/lawyer/firm/members.html
dashboards/lawyer/firm/shared-cases.html
dashboards/lawyer/consultations/list.html
dashboards/lawyer/consultations/chat.html
dashboards/lawyer/consultations/video.html
dashboards/lawyer/consultations/history.html
dashboards/lawyer/cases/list.html
dashboards/lawyer/cases/detail.html
dashboards/lawyer/cases/upload-dokumen.html
dashboards/lawyer/cases/draft-maker.html
dashboards/lawyer/cases/timeline.html
dashboards/lawyer/tools/search-pasal.html
dashboards/lawyer/tools/kalkulator-fee.html
dashboards/lawyer/tools/yurisprudensi.html
dashboards/lawyer/schedule/calendar.html
dashboards/lawyer/schedule/availability.html
dashboards/lawyer/earnings/income.html
dashboards/lawyer/earnings/withdraw.html
dashboards/lawyer/earnings/history.html
dashboards/client/dashboard.html
dashboards/client/profile.html
dashboards/client/vault/kontak.html
dashboards/client/vault/identitas.html
dashboards/client/vault/sertifikat.html
dashboards/client/konsultasi/ai.html
dashboards/client/konsultasi/lawyer.html
dashboards/client/konsultasi/booking.html
dashboards/client/konsultasi/history.html
dashboards/client/cases/list.html
dashboards/client/cases/detail.html
dashboards/client/cases/timeline.html
dashboards/client/cases/dokumen.html
dashboards/client/pembayaran/checkout.html
dashboards/client/pembayaran/invoice.html
dashboards/client/pembayaran/riwayat.html
dashboards/client/notifikasi.html
dashboards/judge/dashboard.html
dashboards/judge/cases/list.html
dashboards/judge/cases/review.html
dashboards/judge/cases/ai-summary.html
dashboards/judge/cases/putusan.html
dashboards/judge/sidang/jadwal.html
dashboards/judge/sidang/ruang.html
dashboards/judge/sidang/teleconference.html
dashboards/judge/sidang/berita-acara.html
dashboards/judge/arsip.html
konsultasi/chat-ai.html
konsultasi/chat-lawyer.html
konsultasi/video-call.html
konsultasi/voice-call.html
konsultasi/upload-dokumen.html
konsultasi/ai-transcription.html
konsultasi/hasil-analisis.html
resources/direktori-hukum.html
courts/daftar.html
courts/detail.html
courts/maps.html
courts/virtual-tour.html
courts/jadwal-sidang.html
cases/daftar.html
cases/detail.html
cases/timeline.html
cases/dokumen.html
cases/evidensi-digital.html
cases/bukti.html
ai/chatbot.html
ai/analisis-kasus.html
ai/rekomendasi-pasal.html
ai/legal-drafting.html
ai/contract-review.html
ai/win-probability.html
ai/cek-dokumen.html
ai/terjemahan-hukum.html
ai/edukasi-ai.html
notifications/email-template.html
notifications/push-template.html
notifications/whatsapp-template.html
notifications/sms-template.html
notifications/system-alert.html
logs/login-log.log
logs/activity-log.log
logs/audit-trail.log
logs/ai-log.log
logs/api-traffic.log
logs/error-log.log
security/access-control.js
security/role-permission.js
security/encryption.js
security/biometric.js
security/mfa-auth.js
security/anti-fraud.js
security/audit-trail.js
assets/css/bootstrap.min.css
assets/css/main.css
assets/css/variables.css
assets/css/theme-dark.css
assets/css/admin.css
assets/css/lawyer.css
assets/css/client.css
assets/css/judge.css
assets/css/chatbot.css
assets/css/animations.css
assets/css/responsive.css
assets/js/core/app.js
assets/js/core/config.js
assets/js/core/router.js
assets/js/core/state-manager.js
assets/js/core/pwa.js
assets/js/core/api-client.js
assets/js/core/event-bus.js
assets/js/realtime/chat.js
assets/js/realtime/webrtc.js
assets/js/realtime/notifications.js
assets/js/realtime/websocket-client.js
assets/js/ai/ai-chat.js
assets/js/ai/ai-analysis.js
assets/js/ai/ai-drafting.js
assets/js/ai/ai-summary.js
assets/js/ai/ai-recommendation.js
assets/js/integrations/payment-gateway.js
assets/js/integrations/e-meterai.js
assets/js/integrations/maps-api.js
assets/locales/id.json
assets/locales/en.json
api/middlewares/auth.js
api/middlewares/rate-limiter.js
api/middlewares/validator.js
api/services/payment-service.js
api/services/email-service.js
api/services/ai-service.js
api/routes/auth-routes.js
api/routes/user-routes.js
api/routes/lawyer-routes.js
api/routes/judge-routes.js
api/routes/case-routes.js
api/routes/court-routes.js
api/routes/payment-routes.js
api/routes/ai-routes.js
api/app.js
data/enums.json
data/users.json
data/lawyers.json
data/judges.json
data/courts.json
data/cases.json
data/consultations.json
data/payments.json
data/notifications.json
utils/vault.js
utils/document-hashing.js
utils/storage.js
utils/validator.js
utils/formatter.js
utils/date.js
utils/uuid.js
config/app-config.js
config/db-config.js
config/api-config.js
config/ai-config.js
config/payment-config.js
config/security-config.js
scripts/seed-users.js
scripts/seed-cases.js
scripts/seed-laws.js
scripts/migrate-db.js
scripts/init-app.js
docs/arsitektur.md
docs/erd.md
docs/flow.md
docs/api.md
docs/deployment.md
docs/manuals/admin-guide.md
docs/manuals/client-guide.md
docs/manuals/lawyer-guide.md
docs/manuals/judge-guide.md
docs/legal-compliance.md
tests/integration/api.test.js
tests/integration/payment.test.js
tests/unit/auth.test.js
tests/unit/ai.test.js
tests/unit/case.test.js
tests/unit/utils.test.js
docker/Dockerfile.dev
docker/Dockerfile.prod
docker/docker-compose.yml
docker/nginx.conf
.github/workflows/test.yml
.github/workflows/deploy.yml
manifest.json
package.json
.env.example
.editorconfig
.eslint.json
.prettierrc
.gitignore
README.md
"@

$dirs -split "`n" | ForEach-Object {
    $d = $_.Trim()
    if ($d -ne '') {
        $path = Join-Path -Path "." -ChildPath $d
        if (-not (Test-Path -Path $path)) {
            New-Item -ItemType Directory -Force -Path $path | Out-Null
            Write-Host "Created array dir $path"
        }
    }
}

$files -split "`n" | ForEach-Object {
    $f = $_.Trim()
    if ($f -ne '') {
        $path = Join-Path -Path "." -ChildPath $f
        if (-not (Test-Path -Path $path)) {
            New-Item -ItemType File -Force -Path $path | Out-Null
            Write-Host "Created file $path"
        }
    }
}
Write-Host "All directories and files have been successfully created!"
